---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: influx-stripprefix
  namespace: monitoring
  labels:
    app.kubernetes.io/name: influx
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/environment: monitoring
spec:
  stripPrefix:
    prefixes:
      - /influx