{{- range $applicationName, $application := .Values.apps | default dict -}}
{{- include "iot-applications.validators.service" (dict "service" $application.service "applicationName" $applicationName) }}
{{- include "iot-applications.validators.ingress" (dict "ingress" $application.ingress "applicationName" $applicationName) }}
{{- if and $application.service.enabled $application.ingress.enabled }}
{{- $ctx := dict "application" $application "name" $applicationName "release" $.Release "chart" $.Chart -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "iot-applications.identifier" $ctx }}
  labels: {{ include "iot-applications.meta.labels" $ctx | nindent 4 }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - {{ include "iot-applications.subdomain" $.Values.VAR_SUBDOMAIN }}{{ $application.labels.component }}.{{ $.Values.VAR_PUBLIC_DOMAIN }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /{{ $application.labels.partOf }}/{{ $applicationName }}
      backendRefs:
        - name: {{ include "iot-applications.identifier" $ctx }}
          port: 80
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: {{ include "iot-applications.identifier" $ctx }}-middleware-stripprefix
{{ end }}
{{ end }}