---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBZyz8+Ba/fZRUBI/Oa6eL88P2CRpXpW/dkeokiGKHFZonfqXG7B8Kfz/mvu8hXsM8Ci3nlO6N7kdbZXLWEaC018D6JiWG8yEByQ9DVqS1sLcAmUk+tin9J3HL5NVXZm2qnekA0v3j637LoxNfNSJbCEt+O26M3BpMFNq6nJVpGks+I0bU2i1huvDFDycFjMPgHDxTZtMloaXadTPunfJoERCwElUXinVF/9+OkhWqCU9bKs9Pb6pY3urUDuQxkwYfHwBMcFKsEGwhRc7TE91uibhWkJPIZvzTdG5IviZPBcI6CsSwA2ys08R6BibMMgTtwiQJ9hlYS9AYBQ8SSROSaUbJnFJITvQU57zdMIuRiWjf7ycPuHBhCwTAeNbZVZHaNg5onLBJ8Hf+nix92FffhEXBQQMa50067T9n4hamxbUJbR5ZCHuu5b4/q+XQ5sTa2gp4tHQdiQFwVt5XCKLrL836mEYedoOsVBQrP2skg8oPIse4GA8hLTC1yNMm/7dLQr0VQ6v4LdDl0RKHXiHsG7Ita9bghOuLxaep5ox91tbJKI2DhbGuWgYx+rnya3HUuEhC1STcNL8SCBtyFDZnfNv38VrsFTUVvq3RglPbgTBSx2ZSBI6PXSoEmIlTBYqk7kyYlocytj6nHx2NZ33jqQqCAjuqtVrR1llntccXn7Q5kpm5V4kigsr5lxL3PLDD+tBugnzhuZ8j+h7AYiA==
    admin-user: AgDDHnJjUJq1Y1whH2vWBJzlBh3OWbeERLPf7WrdSYBdoiBwqV2M8c8bJQvjZfORxr6yVVDZm2oSelnZFBl0/VyyIolpEfMszUTPa3QaQkqOl/Srl6zywASSje1Hh6mlv9VRSbEjGgopMnrUuUQlp6NJYQyEhr4yjZz7hQ12ijTvw+xAaX+eOisvelqzIyYkXc0I1L0YJPUEGDCC1/MsisQMB7ikItOI+onEfM6onuVUNyLKkeq+xTmCQjgCa1J7jkxhUGw/9AIDTi8rWrnLhAAMqZC/p9DNy/o+dJlPypqMf/U6qbWCRV+ZDTawP/91w14z/HxV/UuWUaM+17jzOEcsMn1Rf6IRiHiFOoxMdVgEuJcP5EW29p4AihZvsGTsihgAMmvHdZDKgOlFooBJe4plJeNGoIOW8YuBCbLNiSBIaiNPIK1KGzFADIYSWtm4Y5hEZDrcllwWG8NP3IlLMG2PG5s069woKYlScYY+3o+cNXqlbD6Ek2mteB84yYt/+FL2mbGdhGJ0v2IT5XmJrF1B5G0zig1SSSLcioYVOipSQzx5ITe9GMA8O0xw8NeG1wafq1ihAxH96TdUyYFSjsppjcJsPzALhucLn+CFmPRtKhqt39/5xTFa8rQ0OKl6lNWRGniMxXQl35uz+M6rcHkLqDH4ayyJA7jA2pcTuExXQx1jEBN2bU1kKAYsTH6+6jkWrrn41A==
  template:
    metadata:
      name: grafana-auth
      namespace: monitoring
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-influxdb2-token
  namespace: monitoring
spec:
  encryptedData:
    INFLUX_DB_2_TOKEN: AgBthOSnO1fqQz21s+ESCcebd3Mtnl6uBvhx3PbJdsZzcxUbe6arC74DMlDZA28yYqMsY8bxEy1ySeLZP8Lc9E7nAAKoRshqbtEFTWb6iLW5jJXxUsxWdS+qop20F1jldYnLIPD5cuEmms63bSOSLaM+v7rQnN2dkPfAKWK5J8/j6uUEO/vXhaDDXUoQMjyzYwSl2ACYB1wieHcPAtliNJuxkP+toD1UWjqWjLwz4iseFSlJFJUvCpt+vMTYIt3ELgYADGFOgjKAVc10OdPkOHMMxxB7KOpqU3hMVBbxi+dfflq6nnsSRfAw3i7ikn18biUbNuBTKohA54EjE5JKP0vVLNvqVvk2wgTabJd/LkENmgY4B3KTv4atJuw/BE+P67mvvmsYhswgTbPd4nqYwq/NNDMYFDuCt367bxOzlI18a43mufz94PbspTFnLdyOVFRqmUMUVjq1FoyT8NP91dXIeXy/XZF1ul8pxWwV5+H78cxKB9gm+0xN+ei0C+poeloaXb8ywhbwZ9q43WfnCtLLhDfaGSLEDe0RgOFwAQ5Vf+MokjFivA/aAeIk+c805K4vn8i2o24PtWJ19w4w18n0cgRABrOIyOBOGnmndg/TKFOo7IHNp/1rcjeG6EPgD76NXQK/+hiWEfLImIL7XtkRJ/bvdtmIeP3fKcBUuNXS1vcJxOJ8uf3y9g5pqUrD5XEuOseBwKwQI8BzNy/JhR7XCNV1TzBcXzpkRAvinFShrsyt/0Um+YLVLIclBSEnmDwN5bsNOaqBGSr+q/NGvjPEKBDcDKHFOejD/gpdxTA1Mo/4kfec61Om
  template:
    metadata:
      name: grafana-influxdb2-token
      namespace: monitoring
    type: Opaque
