## @param apps.["*"] Configuration for individual applications
## @param apps.["*"].replicas Number of replicas for the application. Defaults to 1 if not set.

## @param apps.["*"].image Configuration for the application container image
## @param apps.["*"].image.repository Required container image repository
## @param apps.["*"].image.tag Container image tag. Use "latest" for the latest version.
## @param apps.["*"].image.pullPolicy Container image pull policy. Defaults to "IfNotPresent" if not set.

## @param apps.["*"].resources Resource requests and limits for the application container
## @param apps.["*"].resources.requests Resource requests for the application container
## @param apps.["*"].resources.requests.cpu CPU request for the application container. Defaults to "250m" if not set.
## @param apps.["*"].resources.requests.memory Memory request for the application container. Defaults to "250Mi" if not set.
## @param apps.["*"].resources.limits Resource limits for the application container.
## @param apps.["*"].resources.limits.cpu CPU limit for the application container. Defaults to "500m" if not set.
## @param apps.["*"].resources.limits.memory Memory limit for the application container. Defaults to "500Mi" if not set.

## @param apps.["*"].labels Labels to apply to the application pods
## @param apps.["*"].labels.component Component label for the application. Serves also as subdomain for ingress.
## @param apps.["*"].labels.partOf PartOf label for the application. Serves also as base path for ingress.

## @param apps.["*"].service Configuration for the application service
## @param apps.["*"].service.enabled Whether to enable service for the application. Disabling will also disable ingress.
## @param apps.["*"].service.targetPort Target port for the application service, defaults to 80 if not set.

## @param apps.["*"].ingress Configuration for the application ingress
## @param apps.["*"].ingress.enabled Whether to enable ingress for the application. Required.

## @param apps.["*"].templates Optional configuration for Jinja2 templates
## @param apps.["*"].templates.["*"] Configuration for a specific Jinja2 template
## @param apps.["*"].templates.["*"].template Required path to the Jinja2 template file
## @param apps.["*"].templates.["*"].path Required destination path for the rendered template
## @param apps.["*"].templates.["*"].file Required destination file name for the rendered template